name: Deploy with Healing
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install your-dependencies

      - name: Run build
        id: build
        run: |
          set -o pipefail
          npm run build 2>&1 | tee build_output.txt || build_status=$?
          if [ -n "${build_status}" ]; then
            echo "Build failed"
            exit 1
          fi
        env:
          BUILD_OUTPUT_FILE: "build_output.txt"

  commit_changes:
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langchain

      - name: Run your code snippet
        run: |
          python heal-with-deploy.py "build_output.txt"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Commit message"
          git push